version: 1.0.{build}
build:
  verbosity: minimal
deploy:
- provider: GitHub
  tag: myproduct-v$(appveyor_build_version)
  release: product release of v$(appveyor_build_version)
  description: Published from AppVeyor
  auth_token:
    secure: nNJ0tuvMX88/5GPQFV4mtqQe3pRgsJlOd8pvbi0+WeCOsyeNY3L///lRC8pF29wo6J+5b6TPLDDKdKGXveZo9FICP+6k95LkQCvlFzaXb4I=
  artifact: release.zip